name: Create release

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:

  get-tag:
    name: Get latest tag number
    runs-on: ubuntu-22.04
    outputs:
      latest_tag_increment: ${{ steps.latest-tag.outputs.latest_tag_increment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Tags
        id: tags
        run: |
          git fetch --tags
          echo "Tags fetched"
      - name: Get Latest Tag
        id: latest-tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [[ "${{ github.event.pull_request.title }}" == hotfix* ]]; then
            latest_tag_increment=$(echo "$latest_tag + 0.0.1" | bc)
          else
            latest_tag_increment=$(echo "$latest_tag + 0.1" | bc)
          fi
          echo "latest_tag_increment"=${latest_tag_increment} >> $GITHUB_OUTPUT

  release:
    name: Release pushed tag
    needs: get-tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create '${{needs.get-tag.outputs.latest_tag_increment}}' \
              --repo="$GITHUB_REPOSITORY" \
              --generate-notes